DEMO__MQTT__Host: ""
DEMO__MQTT__SlaveHost: ""
DEMO__POSTGRES__ConnMaxLifetime: 0s
DEMO__POSTGRES__Extra: ""
DEMO__POSTGRES__Host: ""
DEMO__POSTGRES__Password: ""
DEMO__POSTGRES__PoolSize: "0"
DEMO__POSTGRES__Port: "0"
DEMO__POSTGRES__SlaveHost: ""
DEMO__POSTGRES__User: ""
GOENV: DEV
