applet:
  name: demo
  version: 0.0.1
tables:
  - name: Demo
    comment: demo table
    defs:
      - type: primary
        fields:
          - ID
      - type: index
        name: I_nickname/BTREE
        fields:
          - Name
      - type: index
        name: I_username
        fields:
          - Username
      - type: unique_index
        name: UI_name
        fields:
          - Name
      - type: unique_index
        name: UI_id_org
        fields:
          - ID
          - OrgID
    fields:
      - name: ID
        field_name: f_id
        type: uint64
        constraints: autoincrement
        comment: primary id
      - name: Name
        field_name: f_name
        type: string
        constraints: default=''
        comment: 姓名
      - name: Nickname
        field_name: f_nickname
        type: string
        constraints: default=''
        comment: 昵称
      - name: Username
        field_name: f_username
        type: string
        constraints: default=''
        comment: 用户名
      - name: Gender
        field_name: f_gender
        type: int
        constraints: default='0'
      - name: Boolean
        field_name: f_boolean
        type: bool
        constraints: default=false
      - name: OrgID
        field_name: f_org_id
        type: uint64
      - name: CreatedAt
        field_name: f_created_at
        type: timestamp
        constraints: default='0'
      - name: UpdatedAt
        field_name: f_updated_at
        type: timestamp
        constraints: default='0'
      - name: DeletedAt
        field_name: f_deleted_at
        type: timestamp
        constraints: default='0'
