name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
env:
  REGISTRY: ghcr.io
  IMAGE: w3bstream/w3bstreamapp

      
jobs:
  ci:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - shell: bash
      run: |
        go mod tidy
        go mod vendor
        git submodule update --init
        cd frontend &&	git pull origin main

